const dataCompany = [{
    "id": 0,
    "company": "重庆市艾尔伴家科技有限公司",
    "position": "售前工程师"
}, {
    "id": 1,
    "company": "重庆新劲旅机电设备有限公司",
    "position": "销售经理"
}, {
    "id": 2,
    "company": "重庆唯申科技有限公司",
    "position": "研发工程师"
}, {
    "id": 3,
    "company": "林同棪（重庆）国际工程技术有限公司",
    "position": "全过程咨询项目经理"
}, {
    "id": 4,
    "company": "重庆云投信息技术有限公司",
    "position": "云平台运维工程师"
}, {
    "id": 5,
    "company": "北京理工大学重庆创新中心",
    "position": "工程师"
}, {
    "id": 6,
    "company": "华东师范大学重庆研究院",
    "position": "材料工程师（材料制备类）"
}, {
    "id": 7,
    "company": "重庆药友制药有限责任公司",
    "position": "制剂研究科学家（博后）"
}, {
    "id": 8,
    "company": "重庆渝富资产经营管理集团有限公司",
    "position": "工业数据分析师"
}, {
    "id": 9,
    "company": "东方红卫星移动通信有限公司",
    "position": "激光通信工程师"
}, {
    "id": 10,
    "company": "新中天环保股份有限公司",
    "position": "博士研发人员"
}, {
    "id": 11,
    "company": "重庆车辆检测研究院有限公司",
    "position": "主动安全及ADAS系统测试检测工程师"
}, {
    "id": 12,
    "company": "重庆市科学技术研究院",
    "position": "硬质合金开发"
}, {
    "id": 13,
    "company": "重庆大数据研究院有限公司",
    "position": "产品经理"
}, {
    "id": 14,
    "company": "上海交大重庆临近空间创新研发中心",
    "position": "飞行器总体设计"
}, {
    "id": 15,
    "company": "重庆两江新区第一人民医院",
    "position": "关节外科医师"
}, {
    "id": 16,
    "company": "重庆图强工程技术咨询有限公司",
    "position": "策划师/助理策划师"
}, {
    "id": 17,
    "company": "重庆高技术创业中心科技孵化园",
    "position": "园区运营经理"
}, {
    "id": 18,
    "company": "重庆励颐拓软件有限公司",
    "position": "CAE软件研发工程师"
}]

export {
    dataCompany
}